
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TonTrain", targetNamespace = "http://example/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TonTrain {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDistance", targetNamespace = "http://example/", className = "mypackage.GetDistance")
    @ResponseWrapper(localName = "getDistanceResponse", targetNamespace = "http://example/", className = "mypackage.GetDistanceResponse")
    @Action(input = "http://example/TonTrain/getDistanceRequest", output = "http://example/TonTrain/getDistanceResponse")
    public double getDistance(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3);

}
