
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TonTrainService", targetNamespace = "http://example/", wsdlLocation = "http://hp-pc:8080/HelloWorld_war3330699556310993984/services/TonTrain?wsdl")
public class TonTrainService
    extends Service
{

    private final static URL TONTRAINSERVICE_WSDL_LOCATION;
    private final static WebServiceException TONTRAINSERVICE_EXCEPTION;
    private final static QName TONTRAINSERVICE_QNAME = new QName("http://example/", "TonTrainService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://hp-pc:8080/HelloWorld_war3330699556310993984/services/TonTrain?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TONTRAINSERVICE_WSDL_LOCATION = url;
        TONTRAINSERVICE_EXCEPTION = e;
    }

    public TonTrainService() {
        super(__getWsdlLocation(), TONTRAINSERVICE_QNAME);
    }

    public TonTrainService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TONTRAINSERVICE_QNAME, features);
    }

    public TonTrainService(URL wsdlLocation) {
        super(wsdlLocation, TONTRAINSERVICE_QNAME);
    }

    public TonTrainService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TONTRAINSERVICE_QNAME, features);
    }

    public TonTrainService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TonTrainService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TonTrain
     */
    @WebEndpoint(name = "TonTrainPort")
    public TonTrain getTonTrainPort() {
        return super.getPort(new QName("http://example/", "TonTrainPort"), TonTrain.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TonTrain
     */
    @WebEndpoint(name = "TonTrainPort")
    public TonTrain getTonTrainPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example/", "TonTrainPort"), TonTrain.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TONTRAINSERVICE_EXCEPTION!= null) {
            throw TONTRAINSERVICE_EXCEPTION;
        }
        return TONTRAINSERVICE_WSDL_LOCATION;
    }

}
